FROM node:10-alpine AS builder

COPY . ./angular8-boot-docker
WORKDIR /angular8-boot-docker
RUN npm i
RUN $(npm bin)/ng build --prod

FROM nginx:1.15.8-alpine
COPY --from=builder /angular8-boot-docker/dist/angular8-boot-docker/ /usr/share/nginx/html